// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-rQYxgtHRgzESaprZKCSxCnfrWCAlFfI',
    appId: '1:626941788878:web:840806d34b2e0ab1d9869f',
    messagingSenderId: '626941788878',
    projectId: 'zenzith-6888a',
    authDomain: 'zenzith-6888a.firebaseapp.com',
    storageBucket: 'zenzith-6888a.appspot.com',
    measurementId: 'G-FEETKB1DME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw5Nlh9iFQ4OM98Bl8BgcrTrBWCJxRKds',
    appId: '1:626941788878:android:ecbb9d578aef436cd9869f',
    messagingSenderId: '626941788878',
    projectId: 'zenzith-6888a',
    storageBucket: 'zenzith-6888a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-WEtzAdk0csn7PH20jDnVpLvq2jZIyvg',
    appId: '1:626941788878:ios:f2b8448caf5aca47d9869f',
    messagingSenderId: '626941788878',
    projectId: 'zenzith-6888a',
    storageBucket: 'zenzith-6888a.appspot.com',
    iosBundleId: 'com.example.zenzith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-WEtzAdk0csn7PH20jDnVpLvq2jZIyvg',
    appId: '1:626941788878:ios:f2b8448caf5aca47d9869f',
    messagingSenderId: '626941788878',
    projectId: 'zenzith-6888a',
    storageBucket: 'zenzith-6888a.appspot.com',
    iosBundleId: 'com.example.zenzith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-rQYxgtHRgzESaprZKCSxCnfrWCAlFfI',
    appId: '1:626941788878:web:6ddcdeebf497533dd9869f',
    messagingSenderId: '626941788878',
    projectId: 'zenzith-6888a',
    authDomain: 'zenzith-6888a.firebaseapp.com',
    storageBucket: 'zenzith-6888a.appspot.com',
    measurementId: 'G-G8B6J9M62T',
  );
}
