// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfa4Za53gciOH1Gd8hbfcZsbEv137fX-8',
    appId: '1:906824225231:web:f4daa7883f9d8f8ce9c2ba',
    messagingSenderId: '906824225231',
    projectId: 'zenzith-app-50c5f',
    authDomain: 'zenzith-app-50c5f.firebaseapp.com',
    databaseURL: 'https://zenzith-app-50c5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zenzith-app-50c5f.appspot.com',
    measurementId: 'G-HQ50D97R2F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzjNP3HvGvqgCH9nkjzShkso6bI3Yrq0A',
    appId: '1:906824225231:android:c290b8385c08a963e9c2ba',
    messagingSenderId: '906824225231',
    projectId: 'zenzith-app-50c5f',
    databaseURL: 'https://zenzith-app-50c5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zenzith-app-50c5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDC8Tisgxo6gs1f9VDLptT-LGRboE6iRdc',
    appId: '1:906824225231:ios:c8b9e2dc3228370be9c2ba',
    messagingSenderId: '906824225231',
    projectId: 'zenzith-app-50c5f',
    databaseURL: 'https://zenzith-app-50c5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zenzith-app-50c5f.appspot.com',
    iosClientId: '906824225231-f09i01e18e30jn4bk8kb0uc3v6lt144a.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenzith',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDC8Tisgxo6gs1f9VDLptT-LGRboE6iRdc',
    appId: '1:906824225231:ios:c8b9e2dc3228370be9c2ba',
    messagingSenderId: '906824225231',
    projectId: 'zenzith-app-50c5f',
    databaseURL: 'https://zenzith-app-50c5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zenzith-app-50c5f.appspot.com',
    iosClientId: '906824225231-f09i01e18e30jn4bk8kb0uc3v6lt144a.apps.googleusercontent.com',
    iosBundleId: 'com.example.zenzith',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfa4Za53gciOH1Gd8hbfcZsbEv137fX-8',
    appId: '1:906824225231:web:787f78ebf07ea845e9c2ba',
    messagingSenderId: '906824225231',
    projectId: 'zenzith-app-50c5f',
    authDomain: 'zenzith-app-50c5f.firebaseapp.com',
    databaseURL: 'https://zenzith-app-50c5f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zenzith-app-50c5f.appspot.com',
    measurementId: 'G-PLKNR219JB',
  );
}
